server:
  port : 8080

spring:
  h2:
    console:
      enabled: true
      path: /console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create
    show-sql:  true

